# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/SEU/cpu_f/cpu/cpu.srcs/sources_1/ip/CM/CM.xci
# IP: The module: 'CM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SEU/cpu_f/cpu/cpu.gen/sources_1/ip/CM/CM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/SEU/cpu_f/cpu/cpu.srcs/sources_1/ip/CM/CM.xci
# IP: The module: 'CM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SEU/cpu_f/cpu/cpu.gen/sources_1/ip/CM/CM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
